SELECT * FROM customer_shopping_behavior

--1.What is the total revenue generated by male vs female customers?
SELECT c.gender, SUM(c.purchase_amount) AS Total_Revenue_M_F 
FROM customer_shopping_behavior AS c
GROUP BY c.gender

--2.Which customer used a discount but still spent more than the average pusrchase amount?
SELECT c.customer_id, c.purchase_amount
FROM customer_shopping_behavior AS c
WHERE c.discount_applied = 'YES' AND c.purchase_amount >= 
(SELECT AVG(purchase_amount) FROM customer_shopping_behavior) 

--3.Which are the top 5 products with the highest average review rating?
SELECT TOP (5) c.item_purchased ,
ROUND(AVG(c.review_rating),2) AS Average
FROM customer_shopping_behavior AS c
GROUP BY c.item_purchased
ORDER BY AVG(c.review_rating) DESC

--4.Compare the average purchase amounts between standard and express shipping
SELECT shipping_type , ROUND(AVG(purchase_amount),2)
FROM customer_shopping_behavior
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type

--5.Do subscribed customers spend more ? compare average spend and total revenue between subscribers and non-subscribers
SELECT c.subscription_status
,COUNT(customer_id) AS Total_customer
,ROUND(AVG(c.purchase_amount),2) AS Average
,ROUND(SUM(c.purchase_amount),2) AS Total
FROM customer_shopping_behavior AS c
WHERE c.subscription_status IN ('YES', 'NO')
GROUP BY c.subscription_status
ORDER BY Total DESC

--6.Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP (5) item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'YES' THEN 1 ELSE 0 END)
/ COUNT(*) ,2) AS discount_rate
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC

--7.Segement customers into New , Returning , and loyal based on their total number of previous purchases , and show the count of each segement
WITH customer_type AS(
SELECT customer_id ,
CASE 
	WHEN previous_purchases = 1 THEN'NEW'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RETURNING'
	ELSE 'LOYAL' 
	END AS customer_segement
FROM customer_shopping_behavior)

SELECT customer_segement , COUNT(*) AS "NUMBER OF CUSTOMERS"
FROM customer_type
GROUP BY customer_segement

--8.What are the top 3 most purchased products within each category
WITH item_counts AS (
SELECT category, item_purchased,
COUNT(customer_id) AS Total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer_shopping_behavior
GROUP BY category , item_purchased)

SELECT category , item_purchased, item_rank, total_orders
FROM item_counts
WHERE item_rank <=3

--9.Are customers who are repeat buyers (more tahn 5 previous purchase) also likely subscribe?
SELECT subscription_status,
COUNT(customer_id) AS repeat_buyers
FROM customer_shopping_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status

--10.What is the revenue contribution of each age group
SELECT c.age_group , SUM(c.purchase_amount) AS Total_Revenue
FROM customer_shopping_behavior AS c
GROUP BY c.age_group
ORDER BY Total_Revenue DESC

